services:
  db:
    image: postgres:16
    container_name: bookstore_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bookstore
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: bookstore_app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/bookstore
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always

volumes:
  postgres_data:
