server:
  port: 8084

spring:

  profiles:
    active: test

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  messages:
    basename: messages
    encoding: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

admin:
  email: ${ADMIN_EMAIL}
  name: ${ADMIN_NAME}
  password-plain: ${ADMIN_PASSWORD}