spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:bookdb;
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true


  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      platform: h2
      continue-on-error: true
      data-locations: classpath:/sql/sql.sql

logging:
  level:
    com.epam.rd.autocode.spring.project: INFO
    org.springframework: WARN
    org.hibernate.SQL: ERROR